language: node_js
node_js:
  - '8'
  - '6'
  - '4'
services:
  - docker
before_install:
  - docker run -it -p 2379:2379 --name etcd -d appcelerator/etcd

script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
